name: Leboncoin Bordeaux Monitor

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Groovy
        run: sudo apt-get update && sudo apt-get install -y groovy

      - name: Run Leboncoin monitor script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: groovy leboncoin-monitor.groovy