name: Leboncoin Bordeaux Monitor

on:
  schedule:
    - cron: '0 */2 * * *' # Runs every 2 hours
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Groovy
        run: sudo apt-get update && sudo apt-get install -y groovy

      - name: Download Jakarta Mail
        run: |
          wget https://repo1.maven.org/maven2/com/sun/mail/jakarta.mail/2.0.1/jakarta.mail-2.0.1.jar -O jakarta.mail-2.0.1.jar

      - name: Run Leboncoin monitor script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: groovy -cp jakarta.mail-2.0.1.jar groovy/leboncoin.groovy